version: "3.9"
services:
  jenkins:
    container_name: jenkins_dev
    image: jenkins/dotnet
    build:
      context: jenkins
    ports:
      - "8080:8080"
    volumes:
      - "/home/jenkins_home:/var/jenkins_home"
    networks:
      - net
  rabbitmq:
    container_name: rabbitmq_dev
    image: rabbitmq:3.9-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "/home/rabbitmq_home:/var/rabbitmq_home"
    networks:
      - net
  mssql:
    container_name: mssql_dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - "/home/mssql_home:/var/mssql_home"
    networks:
      - net
networks:
  net: